services:

  # ========================================
  # BACKEND
  # ========================================

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev

    container_name: sse-backend-dev

    ports:
      - "3000:3000"

    volumes:
      # Código do backend
      - ./backend:/app/backend

      # Evita que o node_modules da máquina
      # sobrescreva o node_modules do container.
      - /app/node_modules

    environment:
      NODE_ENV: development
      PORT: 3000
      REDIS_URL: redis://redis:6379
      CHOKIDAR_USEPOLLING: "true"
      REDIS_CHANNEL: notifications

    depends_on:
      - redis

    restart: unless-stopped


  # ========================================
  # REDIS
  # ========================================

  redis:
    image: redis:7-alpine

    container_name: sse-redis-dev

    ports:
      - "6379:6379"

    restart: unless-stopped




